runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  BOT_API_TOKEN: "5342484465:AAFGKRwvHG1MHOUryA5Bk073UNexQeBGuzw"
  ALERT_API_URL: "https://alerts.com.ua/api/"
  ALERT_API_KEY: "b5876b64165048e8632302aa1fba406aa0f2f4ef"